# Generated by Django 2.2.6 on 2020-02-25 21:11

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=1024)),
                ('correct_answer', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='X5gonResource',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('x5gon_id', models.CharField(max_length=1024)),
                ('title', models.CharField(max_length=1024)),
                ('language', models.CharField(max_length=1024)),
                ('type', models.CharField(max_length=1024)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=512), null=True, size=None)),
                ('concepts', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=512), null=True, size=None)),
                ('description', models.CharField(default='...', max_length=2048, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='X5gonUser',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('x5gon_id', models.CharField(max_length=1024)),
                ('name', models.CharField(default=None, max_length=1024, null=True)),
                ('country', models.CharField(default=None, max_length=1024, null=True)),
                ('interests', models.CharField(default=None, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserResource',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('crown', models.BooleanField(default=False)),
                ('expert_on', models.BooleanField(default=False)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.X5gonResource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.X5gonUser')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionUser',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('given_answer', models.CharField(max_length=1024)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.X5gonUser')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.X5gonResource'),
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=1024)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='backend.X5gonUser')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='backend.X5gonUser')),
            ],
        ),
    ]
